pr: none

stages:
- stage: Build_Bodo_Binary
  displayName: 'Build Bodo Binary'
  jobs:
  - template: buildscripts/azure/azure-arrow-cpp-build-mac-linux.yml
    parameters:
      name: Linux
      vmImage: ubuntu-latest
  - template: buildscripts/azure/azure-arrow-cpp-build-mac-linux.yml
    parameters:
      name: Mac
      vmImage: xcode9-macos10.13