trigger:
- refs/tags/*

pr: none

schedules:
- cron: "0 5 * * *"
  displayName: 'Daily midnight build'
  branches:
    include:
    - master

stages:
- stage: Build_Bodo_Binary
  displayName: 'Build Bodo Binary'
  jobs:
  - job: find_suffix
    pool:
      vmImage: macOS-latest
    steps:
    - script: |
        export BUILD_DATE=`date  +"%Y-%m-%d"`
        if [[ $TRIAL_END_OF_MONTH == 1 ]]; then
          export END_DATE=`date -v+1m -v-$(date +%d)d +"%Y-%m-%d"`
          export d1=`date -v+1m -v-$(date +%d)d +"%s"`
          export d2=`date +"%s"`
          export TRIAL_PERIOD=`expr $(( (d1-d2 + 43200) / 86400 ))`
        elif [[ $TRIAL_END_OF_NEXT_MONTH == 1 ]]; then
          export END_DATE=`date -v+2m -v-$(date +%d)d +"%Y-%m-%d"`
          export d1=`date -v+2m -v-$(date +%d)d +"%s"`
          export d2=`date +"%s"`
          export TRIAL_PERIOD=`expr $(( (d1-d2 + 43200) / 86400 ))`
        elif [[ ! -z "${TRIAL_DAYS}" ]]; then
          export END_DATE=`date -v +${TRIAL_PERIOD}d  +"%m-%d-%y"`
          export TRIAL_PERIOD=${TRIAL_DAYS}
        fi
        
        if [[ ! -z "${MAX_CORE_COUNT}" ]]; then
          export FILE_SUFFIX=built-${BUILD_DATE}-expires-${END_DATE}-max-core-count-${MAX_CORE_COUNT}
        else
          export FILE_SUFFIX=built-${BUILD_DATE}-expires-${END_DATE}
        fi
        echo "##vso[task.setvariable variable=fileSuffix;isOutput=true]$FILE_SUFFIX"
        echo "##vso[task.setvariable variable=trialPeriod;isOutput=true]$TRIAL_PERIOD"
      displayName: 'write FILE_SUFFIX, TRIAL_PERIOD for future use'
      name: suffix_step

  - template: buildscripts/azure/azure-build-binary-linux-macos.yml
    parameters:
      name: Linux
      vmImage: ubuntu-latest
  - template: buildscripts/azure/azure-build-binary-linux-macos.yml
    parameters:
      name: Mac
      vmImage: macOS-latest
  - template: buildscripts/azure/azure-build-binary-windows.yml
    parameters:
      name: Windows
      vmImage: vs2017-win2016

- stage: Test_Bodo_Binary
  displayName: Test Bodo Binary
  jobs:
  - template: buildscripts/azure/azure-test-binary-linux-macos.yml
    parameters:
      name: Mac
      vmImage: macOS-latest
      matrix:
        TEST_1P_SLOW:
          NP: 1
          PYTEST_MARKER: slow
        TEST_2P_SLOW:
          NP: 2
          PYTEST_MARKER: slow
        TEST_3P_SLOW:
          NP: 3
          PYTEST_MARKER: slow
        TEST_1P_NOT_SLOW:
          NP: 1
          PYTEST_MARKER: not slow
        TEST_2P_NOT SLOW:
          NP: 2
          PYTEST_MARKER: not slow
        TEST_3P_NOT_SLOW:
          NP: 3
          PYTEST_MARKER: not slow  
  - template: buildscripts/azure/azure-test-binary-linux-macos.yml
    parameters:
      name: Linux
      vmImage: ubuntu-latest
      matrix:
        TEST_1P_SLOW:
          NP: 1
          PYTEST_MARKER: slow
        TEST_2P_SLOW:
          NP: 2
          PYTEST_MARKER: slow
        TEST_3P_SLOW_FIRST_HALF:
          NP: 3
          PYTEST_MARKER: slow and firsthalf
        TEST_3P_SLOW_SECOND_HALF:
          NP: 3
          PYTEST_MARKER: slow and not firsthalf
        TEST_1P_NOT_SLOW:
          NP: 1
          PYTEST_MARKER: not slow
        TEST_2P_NOT SLOW:
          NP: 2
          PYTEST_MARKER: not slow
        TEST_3P_NOT_SLOW_FIRST_HALF:
          NP: 3
          PYTEST_MARKER: not slow and firsthalf
        TEST_3P_NOT_SLOW_SECOND_HALF:
          NP: 3
          PYTEST_MARKER: not slow and not firsthalf

