version: 0.2

# Link to reference documentation: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

env:
  shell: /bin/bash
  git-credential-helper: yes
  variables:
      CONDA_ENV: "BodoCodeBuild"
 
# Link to reference documentation for batch: https://docs.aws.amazon.com/codebuild/latest/userguide/batch-build-buildspec.html

batch:
  fast-fail: false
  build-list:
    - identifier: Linux_NP_1
      env:
        # List of compute options: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html
        compute-type: BUILD_GENERAL1_MEDIUM
        # List of provided images: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
        image: aws/codebuild/standard:4.0	
        variables:
          PYTEST_MARKER: "not slow"
          NP: "1"
    - identifier: Linux_NP_2_firsthalf
      env:
        compute-type: BUILD_GENERAL1_MEDIUM
        image: aws/codebuild/standard:4.0	
        variables:
          PYTEST_MARKER: "not slow and firsthalf"
          NP: "2"
    - identifier: Linux_NP_2_secondhalf
      env:
        compute-type: BUILD_GENERAL1_MEDIUM
        image: aws/codebuild/standard:4.0	
        variables:
          PYTEST_MARKER: "not slow and not firsthalf"
          NP: "2"
  

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Entered the install phase...
      - buildscripts/setup_conda.sh
      - buildscripts/aws/setup_minio.sh
      - buildscripts/aws/test_installs.sh

  build:
    commands:
      - echo Entered the build phase...
      - buildscripts/build.sh

      
  post_build:
    commands:
      - echo Entered the post-build phase...
      - buildscripts/aws/run_unittests.sh
