version: 0.2

# Actual buildspec file used to run each CI job where NP =1. 
# This file is NOT a template but is shared across the distributed test runs.
# Buildspec Reference: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html


env:
    git-credential-helper: true
    shell: /bin/bash
    variables:
      CONDA_ENV: BodoCodeBuild

phases:
    install:
        commands:
        - echo Entered the install phase...
        - python buildscripts/aws/CI_if_changes.py buildscripts/aws/merge_with_master.sh
        - python buildscripts/aws/CI_if_changes.py buildscripts/setup_conda.sh
        - python buildscripts/aws/CI_if_changes.py buildscripts/aws/setup_minio.sh
        - python buildscripts/aws/CI_if_changes.py buildscripts/aws/test_installs.sh
    build:
        commands:
        - echo Entered the build phase...
        - python buildscripts/aws/CI_if_changes.py buildscripts/build.sh
    post_build:
        commands:
        - echo Entered the post-build phase...
        - python buildscripts/aws/CI_if_changes.py buildscripts/aws/run_unittests.sh

artifacts:
  files:
    - ./.coverage
  name: $(buildscripts/aws/get_sonar_artifact_name.sh)