version: 0.2

# Link to reference documentation: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

env:
  shell: /bin/bash
  git-credential-helper: true
  variables:
      CONDA_ENV: "BodoCodeBuild"
      ENGINE_E2E_TESTS: "engine-e2e-tests"

phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
        - echo Conda Setup and Test Installs
        - buildscripts/get_miniconda.sh


    build:
        commands:
        - echo Building Obfuscated Binary
        - buildscripts/aws/build_obfuscated.sh


    post_build:
        commands:
        - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
        - buildscripts/aws/publish_binary.sh
        - buildscripts/aws/run_nightly_tests.sh
