bversion: 0.2

# Link to reference documentation: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

env:
  shell: bash
  git-credential-helper: yes
  variables:
      CONDA_ENV: "BodoCodeBuild"

phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
        - echo Conda Setup and Test Installs
        - buildscripts/setup_conda.sh
        - buildscripts/aws/test_installs.sh


    build:
        commands:
        - echo Building Obfuscated Binary
        - buildscripts/aws/build_obfuscated.sh


    post_build:
        commands:
        - buildscripts/aws/publish_binary.sh
