{% set version = "2.8.0rc1" %}

package:
  name: h5py
  version: {{ version }}

source:
   url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - hdf5
    - python 3.6.*
    - setuptools
    - numpy
    - cython
    - pkgconfig
    - six
    - mpich # [not win]

  run:
    - python
    - numpy
    - cython
    - pkgconfig
    - six
    - mpich # [not win]
    - hdf5

test:
  imports:
    - h5py


about:
  home: https://github.com/h5py/h5py.git
  license: BSD
  license_file: licenses/license.txt
  summary: Python wrappers for hdf5 library
