parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  dependsOn: find_suffix
  variables:
    suffix: $[ dependencies.find_suffix.outputs['suffix_step.fileSuffix'] ]
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
    displayName: 'Use Python $(python.version)'

  - script: |
      pip install astunparse
      chmod +x buildscripts/remove_docstring.py
    displayName: 'Prepare to build'

  - script: |
      if [[ "${{ parameters.name }}" == "Linux" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
      fi
      chmod +x miniconda.sh
      ./miniconda.sh -b
      export PATH=$HOME/miniconda3/bin:${PATH}
    displayName: 'Setup Miniconda'

  - script: |
      export PATH=$HOME/miniconda3/bin:$PATH
      source activate bodo_build
      conda install -y flake8
      flake8 bodo
    displayName: 'Flake8'

  - script: |
      export PATH=$HOME/miniconda3/bin:${PATH}
      conda create -y -n bodo_build conda-build anaconda-client conda-verify
    displayName: 'Create Conda Env'
    
  - script: |
      export PATH=$HOME/miniconda3/bin:${PATH}
      source activate bodo_build
      if [[ $OBFUSCATE == 1 ]]; then
        conda install -y astor
        cd obfuscation
        ./do_obfuscation.py
      else
        echo "Skipping Obfuscation"
      fi
    displayName: 'Obfuscation'

  - script: |
      export PATH=$HOME/miniconda3/bin:${PATH}
      source activate bodo_build
      cd buildscripts/bodo-conda-recipe/
      export CHECK_LICENSE_EXPIRED=$(CHECK_LICENSE_EXPIRED)
      export CHECK_LICENSE_CORE_COUNT=$(CHECK_LICENSE_CORE_COUNT)
      conda-build . -c bodo.ai -c conda-forge --no-test
    displayName: 'Conda build Bodo'

  - script: |
      export PATH=$HOME/miniconda3/bin:${PATH}
      source activate bodo_build
      cd $(System.DefaultWorkingDirectory)
      mkdir bodo-inc
      if [[ "${{ parameters.name }}" == "Linux" ]]; then
        mkdir bodo-inc/linux-64
        cp $(HOME)/miniconda3/envs/bodo_build/conda-bld/linux-64/bodo*.tar.bz2 bodo-inc/linux-64/
      else
        mkdir bodo-inc/osx-64
        cp $(HOME)/miniconda3/envs/bodo_build/conda-bld/osx-64/bodo*.tar.bz2 bodo-inc/osx-64/
      fi
      conda index bodo-inc/

    displayName: 'index bodo-inc'
 
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/bodo-inc'
      includeRootFolder: false
      archiveFile: $(Build.ArtifactStagingDirectory)/${{ parameters.name }}-bodo-inc-$(suffix).zip
      replaceExistingArchive: true 
    displayName: "Archive files"
    
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)/${{ parameters.name }}-bodo-inc-$(suffix).zip
      artifactName: bodo-inc
    displayName: "Publish Artifact"
