parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  pool: 
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 11
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}
      
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
    displayName: 'Use Python $(python.version)'

  - script: |
      buildscripts/setup_conda.sh
      export PATH=$HOME/miniconda3/bin:$PATH
    displayName: 'Setup Miniconda'

  - script: |
      export PATH=$HOME/miniconda3/bin:$PATH
      source activate $CONDA_ENV
      HDF5_DIR=$CONDA_PREFIX python setup.py develop
    displayName: 'Build'

  - script: |
      export PATH=$HOME/miniconda3/bin:$PATH
      source activate $CONDA_ENV
      pip install pytest pytest-azurepipelines
      if [["$NP" == 1]]; then
        pytest -s -v -W ignore bodo/tests/
      else
        mpiexec -n $NP pytest -s -v -W ignore bodo/tests/
      fi
    displayName: 'Test'
