{% set version = "1.10.1" %}
{% set maj_min_ver = ".".join(version.split(".")[:2]) %}

package:
  name: hdf5
  version: {{ version }}

source:
  fn: hdf5-{{ version }}.tar.gz
  url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-{{ maj_min_ver }}/hdf5-{{ version }}/src/hdf5-{{ version }}.tar.gz
  sha256: 048a9d149fb99aaa1680a712963f5a78e9c43b588d0e79d55e06760ec377c172

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.1   # [win]
    - python 3.6.*
    - mpich # [not win]
  run:
    - mpich # [not win]


about:
  home: https://www.hdfgroup.org/
  license: BSD
  license_file: COPYING
  summary: Parallel HDF5 library
