package:
  name: bodo
  version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  script_env:
  - TRIAL_PERIOD
  - MAX_CORE_COUNT

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python 3.7
    - setuptools
    - numba 0.48.*
    - numpy
    - pandas >=1.0.0
    - pyarrow =0.16.0
    - boost-cpp
    - hdf5 * mpi_mpich_* # [not win]
    - h5py
    - mpich # [not win]
    - impi-devel # [win]
    - impi_rt # [win]
    - vc # [win]
    - vs2015_runtime # [win]
    - vs2015_win-64 # [win]
    
  run:
    - python 3.7
    - {{ pin_compatible('numpy') }}
    - pandas >=1.0.0
    - pyarrow =0.16.0
    - boost-cpp
    - numba 0.48.*
    - mpich # [not win]
    - impi_rt # [win]
    - vs2015_runtime # [win]
    - vs2015_win-64 # [win]


test:
  imports:
    - bodo
  source_files:
    - examples/pi.py


about:
  home: https://www.bodo-inc.com/
  license: Proprietary
  license_file: LICENSE.md
  summary: Bodo Core Engine for analytics
