package:
  name: bodo
  version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  script_env:
  - TRIAL_PERIOD

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - setuptools
    - numba 0.46.*
    - numpy
    - pandas >=0.25
    - pyarrow >=0.11
    - arrow-cpp
    - boost
    - hdf5
    - h5py
    - mpich # [not win]
    - impi-devel # [win]
    - impi_rt # [win]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas >=0.25
    - pyarrow >=0.11
    - arrow-cpp
    - boost
    - numba 0.46.*
    - mpich # [not win]
    - impi_rt # [win]

test:
  requires:
    - h5py
    - scipy
    - pytest
  imports:
    - bodo


about:
  home: https://www.bodo-inc.com/
  license: Proprietary
  license_file: LICENSE.md
  summary: Bodo Core Engine for analytics
