package:
  name: hpat
  version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python 3.6.*
    - setuptools
    - numba 0.38.*
    - numpy 1.14.*
    - pandas
    - mpich # [not win]
    - pyarrow 0.9.*
    - boost
    - hdf5
    - h5py
    - daal-devel
    - opencv
    - hpat-parquet-reader

  run:
    - python 3.6.*
    - numpy 1.14.*
    - pandas
    - mpich # [not win]
    - pyarrow 0.9.*
    - boost
    - numba 0.38.*
    - hdf5
    - h5py
    - hpat-parquet-reader

test:
  imports:
    - hpat


about:
  home: https://github.com/IntelLabs/hpat
  license: BSD
  license_file: LICENSE.md
  summary: A compiler-based big data framework in Python
