package:
   name: numba
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ../../../numba

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  entry_points:
    - pycc = numba.pycc:main
    - numba = numba.numba_entry:main
  script_env:
    - PY_VCRUNTIME_REDIST

requirements:
  # build and run dependencies are duplicated to avoid setuptools issues
  # when we also set install_requires in setup.py
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python 3.6.*
    - numpy 1.13.*
    - setuptools
    # On channel https://anaconda.org/numba/
    - llvmlite
    - funcsigs                 # [py27]
    - singledispatch           # [py27]
  run:
    - python
    - numpy
    # On channel https://anaconda.org/numba/
    - llvmlite
    - funcsigs                 # [py27]
    - singledispatch           # [py27]
    # Need these for AOT. Do not init msvc as it may not be present
    - {{ compiler('c') }}      # [not win]
    - {{ compiler('cxx') }}    # [not win]
test:
  requires:
    - jinja2
    # Required to test optional Numba features
    - cffi
    - scipy
    - ipython
    - setuptools
  files:
    - mandel.py
  commands:
    # Check Numba executables are there
    - pycc -h
    - numba -h
    # run system info tool
    - numba -s
    # Check test discovery works
    - python -m numba.tests.test_runtests
    # Run the whole test suite
    - python -m numba.runtests -m -b

about:
  home: http://numba.pydata.org/
  license: BSD
  license_file: LICENSE
  summary: a just-in-time Python function compiler based on LLVM
